"""Integration test for migration 0022 identity column round-trip.

Exercises the 0021 -> 0022 -> 0021 -> 0022 migration cycle and catches the
class of bug where downgrade() leaves the column in an inconsistent state
(missing sequence, missing default expression) that prevents a subsequent
upgrade() from re-applying GENERATED ALWAYS AS IDENTITY cleanly.

Schema assertions use pg_attribute.attidentity, pg_sequences, and pg_attrdef
to prove the column is in the expected state after each migration step.
"""

from __future__ import annotations

import asyncpg
import pytest

from tests.integration._alembic_runner import run_alembic

pytestmark = [
    pytest.mark.asyncio(loop_scope="session"),
    pytest.mark.integration,
]


# ---------------------------------------------------------------------------
# Schema-shape helpers
# ---------------------------------------------------------------------------


async def _attidentity(pool: asyncpg.Pool) -> str:
    """Return pg_attribute.attidentity for audit_log.id as a str.

    '' = not an identity column
    'a' = GENERATED ALWAYS
    'd' = GENERATED BY DEFAULT

    asyncpg returns the PostgreSQL "char" type (single-byte internal type) as
    bytes; this helper decodes to str so callers can compare against '' or 'a'.
    """
    async with pool.acquire() as conn:
        val = await conn.fetchval(
            """
            SELECT attidentity
            FROM pg_attribute
            JOIN pg_class ON pg_attribute.attrelid = pg_class.oid
            WHERE pg_class.relname = 'audit_log'
              AND pg_attribute.attname = 'id'
            """
        )
    if val is None:
        return ""
    if isinstance(val, bytes | bytearray):
        return val.decode("ascii")
    return str(val)


async def _seq_exists(pool: asyncpg.Pool) -> bool:
    """Return True if the audit_log_id_seq sequence exists in pg_sequences."""
    async with pool.acquire() as conn:
        val = await conn.fetchval(
            "SELECT 1 FROM pg_sequences WHERE sequencename = 'audit_log_id_seq'"
        )
    return val is not None


async def _attrdef_exists(pool: asyncpg.Pool) -> bool:
    """Return True if audit_log.id has a default expression in pg_attrdef."""
    async with pool.acquire() as conn:
        val = await conn.fetchval(
            """
            SELECT 1
            FROM pg_attrdef
            JOIN pg_attribute
                ON pg_attrdef.adrelid = pg_attribute.attrelid
               AND pg_attrdef.adnum   = pg_attribute.attnum
            JOIN pg_class
                ON pg_attribute.attrelid = pg_class.oid
            WHERE pg_class.relname     = 'audit_log'
              AND pg_attribute.attname = 'id'
            """
        )
    return val is not None


# ---------------------------------------------------------------------------
# Round-trip test
# ---------------------------------------------------------------------------


async def test_0022_identity_roundtrip(
    admin_pool: asyncpg.Pool,
) -> None:
    """0021 -> 0022 -> 0021 -> 0022 round-trip proves downgrade() is safe.

    The downgrade() path of 0022_audit_log_identity must leave the column in
    the BIGSERIAL-compatible state (sequence exists, default expression wired)
    so that a subsequent upgrade() can re-apply GENERATED ALWAYS AS IDENTITY
    cleanly.

    Steps wrapped in try/finally so the session DB is always restored to head
    regardless of assertion failures.
    """
    from tests.conftest import RLS_BOOTSTRAP_URL

    # Step 1: Precondition -- ensure DB is at head before mutating.
    up_pre = run_alembic(RLS_BOOTSTRAP_URL, "upgrade", "head")
    assert up_pre.returncode == 0, (
        f"precondition upgrade head failed:\n"
        f"stdout:\n{up_pre.stdout}\n"
        f"stderr:\n{up_pre.stderr}"
    )
    assert (
        await _attidentity(admin_pool) == "a"
    ), "expected GENERATED ALWAYS (attidentity='a') at head before round-trip"
    assert not await _seq_exists(
        admin_pool
    ), "expected audit_log_id_seq to be absent at head before round-trip"
    assert not await _attrdef_exists(
        admin_pool
    ), "expected no default expression on audit_log.id at head before round-trip"

    try:
        # Step 2: Downgrade from 0022 back to 0021.
        # This is the line that fails before the migration bug-fix lands with
        # the unterminated quoted string in downgrade()'s DO block.
        down = run_alembic(RLS_BOOTSTRAP_URL, "downgrade", "0021_perf_audit_log_actor_idx")
        assert (
            down.returncode == 0
        ), f"downgrade to 0021 failed:\nstdout:\n{down.stdout}\nstderr:\n{down.stderr}"

        # Step 3: Post-downgrade schema assertions.
        assert (
            await _attidentity(admin_pool) == ""
        ), "expected no identity marker (attidentity='') after downgrade to 0021"
        assert await _seq_exists(
            admin_pool
        ), "expected audit_log_id_seq to exist after downgrade to 0021"
        assert await _attrdef_exists(
            admin_pool
        ), "expected default expression on audit_log.id after downgrade to 0021"

        # Step 4: Re-upgrade to 0022.
        up_0022 = run_alembic(RLS_BOOTSTRAP_URL, "upgrade", "0022_audit_log_identity")
        assert (
            up_0022.returncode == 0
        ), f"re-upgrade to 0022 failed:\nstdout:\n{up_0022.stdout}\nstderr:\n{up_0022.stderr}"

        # Step 5: Post-re-upgrade schema assertions.
        assert (
            await _attidentity(admin_pool) == "a"
        ), "expected GENERATED ALWAYS (attidentity='a') after upgrade to 0022"
        assert not await _seq_exists(
            admin_pool
        ), "expected audit_log_id_seq to be absent after upgrade to 0022"
        assert not await _attrdef_exists(
            admin_pool
        ), "expected no default expression on audit_log.id after upgrade to 0022"

    finally:
        # Step 6: Restore session DB to head unconditionally.
        up_restore = run_alembic(RLS_BOOTSTRAP_URL, "upgrade", "head")
        if up_restore.returncode != 0:
            pytest.fail(
                f"restore upgrade head failed -- session DB left at 0022:\n"
                f"stdout:\n{up_restore.stdout}\n"
                f"stderr:\n{up_restore.stderr}"
            )
